---
swagger: "2.0"
info:
  description: ""
  version: "1.5.0"
  title: "TimeSeriesDataCapture"
  contact:
    name: "TimeSeriesDataCapture@gmail.com"
    email: "TimeSeriesDataCapture@gmail.com"
#host: "timeseriesdatacapture-import.herokuapp.com:443"
host : tsdc.herokuapp.com:443"
#host: "localhost:8001"
basePath: "/apis"
tags:
- name: "ImportAPI"
  description: "Getting components from file storage"
schemes:
- "https"
#- "http"
paths:
  /components:
    get:
      tags:
      - "ImportAPI"
      summary: "Gets IDs available for import"
      description: "Gets all the component IDs available for import"
      operationId: "getComponentIDs"
      produces:
      - "application/json"
      parameters:
      - name: "folderID"
        in: "query"
        description: "Specifies which folder to search"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Array of component objects"
            items:
              type: "string"
              example: "component_id"
              description: "specific component ID"
        400:
          description: "Bad request"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "ImportAPI"
  /component/{componentID}:
    get:
      tags:
      - "ImportAPI"
      summary: "Gets a specific component"
      description: "gets a specific component by component ID"
      operationId: "getComponent"
      produces:
      - "application/json"
      parameters:
      - name: "componentID"
        in: "path"
        description: "Component ID specifies which component to download "
        required: true
        type: "string"
      - name: "algorithmID"
        in: "query"
        description: "alogrithm used to calculate Rth"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "file"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "ImportAPI"
  /component/{componentID}/preview:
    get:
      tags:
      - "ImportAPI"
      summary: "Gets a specific component"
      description: "gets a specific component by component ID from oneDrive"
      operationId: "getComponentPreview"
      produces:
      - "application/json"
      parameters:
      - name: "componentID"
        in: "path"
        description: "Component ID specifies which component to download "
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              type: 'string'
              example: 'run object'
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "ImportAPI"
  /operations:
    get:
      tags:
      - "ImportAPI"
      summary: "Gets supported operations"
      description: "Gets currently supported operations"
      operationId: "getOperations"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Array of operations"
            items:
              type: "string"
              example: "Compare"
        400:
          description: ""
      x-swagger-router-controller: "ImportAPI"
definitions: {
  
}
